// Loading Status
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

// Carousel
export const GET_MAIN_CAROUSEL_IMAGES = 'GET_MAIN_CAROUSEL_IMAGES';
export const GET_CAROUSEL_IMAGES = 'GET_CAROUSEL_IMAGES';
export const RESET_CURRENT_ENLARGED_IMAGE = 'RESET_CURRENT_ENLARGED_IMAGE';
export const SET_CURRENT_ENLARGED_IMAGE = 'SET_CURRENT_ENLARGED_IMAGE';
