// Login
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Loading Status
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

// Main
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_ELEMENTS = 'LOAD_ELEMENTS';

// Admin
export const LOAD_ADMIN_CATEGORIES = 'LOAD_ADMIN_CATEGORIES';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const CANCEL_EDIT_CATEGORY = 'CANCEL_EDIT_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const SET_REMOVING_CATEGORY = 'SET_REMOVING_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SET_ADMIN_CATEGORY = 'SET_ADMIN_CATEGORY';
export const SET_ADMIN_ELEMENT = 'SET_ADMIN_ELEMENT';
export const LOAD_ADMIN_QUOTATION_BASES = 'LOAD_ADMIN_QUOTATION_BASES';
export const EDIT_QUOTATION_BASE = 'EDIT_QUOTATION_BASE';
export const CANCEL_EDIT_QUOTATION_BASE = 'CANCEL_EDIT_QUOTATION_BASE';
export const UPDATE_QUOTATION_BASE = 'UPDATE_QUOTATION_BASE';
export const SAVE_QUOTATION_BASE = 'SAVE_QUOTATION_BASE';
export const SET_REMOVING_QUOTATION_BASE = 'SET_REMOVING_QUOTATION_BASE';
export const REMOVE_QUOTATION_BASE = 'REMOVE_QUOTATION_BASE';

// Carousel
export const GET_MAIN_CAROUSEL_IMAGES = 'GET_MAIN_CAROUSEL_IMAGES';
export const GET_CAROUSEL_IMAGES = 'GET_CAROUSEL_IMAGES';
export const RESET_CURRENT_ENLARGED_IMAGE = 'RESET_CURRENT_ENLARGED_IMAGE';
export const SET_CURRENT_ENLARGED_IMAGE = 'SET_CURRENT_ENLARGED_IMAGE';
export const TRIGGER_EDIT_IMAGE = 'TRIGGER_EDIT_IMAGE';
export const CANCEL_IMAGE_EDITING = 'CANCEL_IMAGE_EDITING';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const UPDATE_IMAGE_DATA = 'UPDATE_IMAGE_DATA';
export const SAVE_IMAGE = 'SAVE_IMAGE';
export const SET_REMOVING_IMAGE = 'SET_REMOVING_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
